### ISSUE TITLE
Stargaze Collections

### ISSUE THREAD

**Issue by Beastmode93** [public-awesome/stargaze-studio#190]
![Stargaze-error](https://github.com/public-awesome/stargaze-studio/assets/139662382/eeab5951-c44e-440b-8d1c-5530b641b207)

Randomly the Collections that I make will disappear from the launchpad. The NFTs that have been minted remain but no more can be minted.

**Comment by MightOfOaks** [comment]
> Randomly the Collections that I make will disappear from the launchpad. The NFTs that have been minted remain but no more can be minted.

It is possible that they might be getting flagged for including explicit content.

In any case, this is not a Stargaze Studio related issue. Please join the Discord server (https://discord.gg/XfyZQUDg) and use the #support channel to create a ticket.
